# Use a Node.js 20 base image
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app/backend

# set docker env to development
ENV ENV=development

COPY backend /app/backend
# Copy package files - note the context is the parent directory
COPY backend/package.json backend/pnpm-lock.yaml ./

# Install npm packages
RUN npm install -g pnpm

# Setup pnpm global directory -- used for installing global packages
ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="${PNPM_HOME}:$PATH"
ENV SHELL="/bin/sh"
RUN pnpm setup

# RUN apk add --no-cache python3 make g++ gcc

RUN pnpm install
RUN pnpm install -g tsx

# Use entrypoint to allow different commands
ENTRYPOINT ["pnpm", "run"]
# Default to dev if no command specified
CMD ["dev"]
